"""
Email Handler for Python Tip Agent
Sends email notifications with approval links
"""

import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Dict
from pathlib import Path


class EmailHandler:
    """Handles email notifications for tip approval"""
    
    def __init__(self):
        self.smtp_server = os.getenv("SMTP_SERVER", "smtp.gmail.com")
        self.smtp_port = int(os.getenv("SMTP_PORT", "587"))
        self.sender_email = os.getenv("SENDER_EMAIL")
        self.sender_password = os.getenv("SENDER_PASSWORD")
        self.recipient_email = os.getenv("RECIPIENT_EMAIL", "Sheida.shaban18@gmail.com")
        self.approval_base_url = os.getenv("APPROVAL_BASE_URL", "http://localhost:5000")
    
    def send_approval_email(self, tip_data: Dict[str, str], approval_token: str) -> bool:
        """
        Send an email with the tip and approval/reject links
        
        Args:
            tip_data: Dictionary containing tip information
            approval_token: Unique token for this tip approval
            
        Returns:
            True if email sent successfully, False otherwise
        """
        if not self.sender_email or not self.sender_password:
            print("Email credentials not configured. Skipping email.")
            return False
        
        try:
            # Create message
            message = MIMEMultipart("alternative")
            message["Subject"] = f"🐍 Daily Python Tip: {tip_data['headline']}"
            message["From"] = self.sender_email
            message["To"] = self.recipient_email
            
            # Read the tip content (either from 'code' key for new format or 'content' for old)
            if 'code' in tip_data and 'explanation' in tip_data:
                # New format with separate code and explanation
                tip_code = tip_data['code']
                tip_explanation = tip_data['explanation']
            else:
                # Old format with combined content
                tip_content = tip_data['content']
                tip_code = tip_content
                tip_explanation = ""
            
            # Create approve and reject URLs (GitHub Actions)
            approve_url = "https://github.com/Sheidashaban/github_actions/actions/workflows/approve-tip.yml"
            reject_url = "https://github.com/Sheidashaban/github_actions/actions/workflows/reject-tip.yml"
            
            # Create plain text version
            text_content = f"""
Daily Python Tip
================

{tip_data['headline']}

{tip_explanation if 'explanation' in tip_data else ''}

{tip_code if 'code' in tip_data else tip_content}

---

ACTIONS:
1. To APPROVE: Go to {approve_url}
   Click "Run workflow" button, then click green "Run workflow"
   
2. To REJECT: Go to {reject_url}
   Click "Run workflow" button, then click green "Run workflow"

---
Generated by Python Tip Agent
            """
            
            # Create HTML version
            html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        .container {{
            background-color: white;
            border-radius: 10px;
            padding: 30px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 25px;
        }}
        h1 {{
            margin: 0;
            font-size: 24px;
        }}
        .tip-content {{
            background-color: #f8f9fa;
            border-left: 4px solid #667eea;
            padding: 20px;
            margin: 20px 0;
            border-radius: 4px;
        }}
        pre {{
            background-color: #282c34;
            color: #abb2bf;
            padding: 20px;
            border-radius: 8px;
            overflow-x: auto;
            font-family: 'Courier New', monospace;
            font-size: 14px;
            line-height: 1.5;
        }}
        .actions {{
            margin-top: 30px;
            padding: 20px;
            background-color: #f8f9fa;
            border-radius: 8px;
            text-align: center;
        }}
        .button {{
            display: inline-block;
            padding: 12px 30px;
            margin: 10px;
            text-decoration: none;
            border-radius: 6px;
            font-weight: bold;
            font-size: 16px;
            transition: transform 0.2s;
        }}
        .button:hover {{
            transform: translateY(-2px);
        }}
        .approve {{
            background-color: #28a745;
            color: white;
        }}
        .reject {{
            background-color: #dc3545;
            color: white;
        }}
        .footer {{
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #e0e0e0;
            text-align: center;
            color: #666;
            font-size: 14px;
        }}
        code {{
            background-color: #e8e8e8;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🐍 Daily Python Tip</h1>
        </div>
        
        <h2>{tip_data['headline']}</h2>
        
        <div class="tip-content">
            {f'<p>{tip_explanation}</p>' if 'explanation' in tip_data else ''}
            <pre>{tip_code if 'code' in tip_data else tip_content}</pre>
        </div>
        
        <div class="actions">
            <h3>Review this tip:</h3>
            <p><strong>This tip is saved as a DRAFT and NOT yet published.</strong></p>
            <p>To approve or reject:</p>
            
            <div style="margin: 20px 0; padding: 15px; background: #f0f9ff; border-radius: 8px; border-left: 4px solid #3b82f6;">
                <strong>✅ To APPROVE:</strong>
                <ol style="margin: 10px 0;">
                    <li>Go to: <a href="{approve_url}">Approve Workflow</a></li>
                    <li>Click "Run workflow" button (right side)</li>
                    <li>Click green "Run workflow" button</li>
                    <li>Tip will be published to Python_Tips!</li>
                </ol>
            </div>
            
            <div style="margin: 20px 0; padding: 15px; background: #fef2f2; border-radius: 8px; border-left: 4px solid #ef4444;">
                <strong>❌ To REJECT:</strong>
                <ol style="margin: 10px 0;">
                    <li>Go to: <a href="{reject_url}">Reject Workflow</a></li>
                    <li>Click "Run workflow" button (right side)</li>
                    <li>Click green "Run workflow" button</li>
                    <li>Tip will be deleted permanently</li>
                </ol>
            </div>
            
            <a href="{approve_url}" class="button approve">✅ Go to Approve Workflow</a>
            <a href="{reject_url}" class="button reject">❌ Go to Reject Workflow</a>
        </div>
        
        <div class="footer">
            <p><strong>Filename:</strong> <code>{tip_data['filename']}</code></p>
            <p>Generated by Python Tip Agent on {tip_data['date'][:10]}</p>
        </div>
    </div>
</body>
</html>
            """
            
            # Attach both versions
            part1 = MIMEText(text_content, "plain")
            part2 = MIMEText(html_content, "html")
            message.attach(part1)
            message.attach(part2)
            
            # Send email
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.sender_email, self.sender_password)
                server.send_message(message)
            
            print(f"[OK] Email sent successfully to {self.recipient_email}")
            return True
            
        except Exception as e:
            print(f"[ERROR] Error sending email: {e}")
            return False


if __name__ == "__main__":
    # Test the email handler
    from dotenv import load_dotenv
    load_dotenv()
    
    handler = EmailHandler()
    
    test_tip = {
        "headline": "Using enumerate for index and value",
        "shortname": "using_enumerate_for_index_and_value",
        "content": """# Example code
for index, item in enumerate(['a', 'b', 'c']):
    print(f"{index}: {item}")""",
        "filename": "Python_tip_test.py",
        "date": "2025-11-02"
    }
    
    test_token = "test_token_123"
    handler.send_approval_email(test_tip, test_token)

